slogan: "身世酒杯中，万事皆空。"

# show_heart: false

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    # icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    # icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    # icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    # icon: "fa fa-user"
  - title: RSS
    url: atom.xml
    intro: "Subscribe me."
    # icon: "fa fa-user"

links:
  # - title: 
  #   url: https://github.com/Ares-X/hexo-theme-freemind.bithack
  #   intro: ""
  #   icon: false

  # - title: "My LinkedIn"
  #   url: http://www.linkedin.com/in/xxx
  #   intro: "My Linkin account."
  #   icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: 
fancybox: true
favicon: favicon.png
#duoshuo_shortname: 


# Analytics (change to yours)
google_analytics:
  enable: true
  siteid: G-LLD9P3JH76


# search
swiftype_key: Qokm7azGTvyEEXDD5z_V
#valine comment (change to yours)
valine: 
  enable: true
  appId: 'IfL8bDN7TcQtxsNT8fFuTqfs-gzGzoHsz'
  appKey: 'Yrn52pQO2efYU8eydgAlY63M'
  placeholder: "提交评论时留下邮箱收到回复后将自动通知"
  visitor: true
  avatar: 'monsterid'
  requiredFields: ['nick']

  